// 02-react/bug-tracker-app/src/Greeter.jsx
import React from "react"

function Greeter(){
    const [userName, setUserName] = React.useState('dummy')
    const [message, setMessage] = React.useState('[default message]')
    const onTxtUserNameChange = (evt) => {
        setUserName(evt.target.value)
    }
    const onBtnGreetClick = () => {
        const greetMsg = `Hi ${userName}, Have a nice day!`
        setMessage(greetMsg)
    }
    return (
        <div>
            <h1>Greeter</h1>
            <hr />
            <label htmlFor="">UserName :</label>
            <input type="text" onChange={onTxtUserNameChange} />
            <button onClick={onBtnGreetClick}>Greet</button>
            <div>{message}</div>
            {/* <div>The user name : {userName}</div> */}
        </div>
    )
}

export default Greeter

// 03-angular/test-app/src/app/greeter/greeter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-greeter',
  templateUrl: './greeter.component.html',
  styleUrls: ['./greeter.component.css']
})
export class GreeterComponent {
  
  greetMsg = ""
  userName = ""

  onBtnGreetClick(){
    this.greetMsg = `Hi ${this.userName}, Have a nice day!`
  }
  onTxtUserNameChange(evt:any) {
    this.userName = evt.target.value
  }
}

<h3>Greeter</h3>
<hr>
<label for="">User Name :</label>
<input type="text" (input)="onTxtUserNameChange($event)">
<button (click)="onBtnGreetClick()">Greet</button>
<div>{{ greetMsg }}</div>
